version: '3'

includes:
  reviung34:
    taskfile: ./Taskfile-keyboard.yml
    vars:
      USERNAME: hannes
      KEYBOARD: reviung/reviung34
  reviung41-kb2040:
    taskfile: ./Taskfile-keyboard.yml
    vars:
      USERNAME: hannes
      KEYBOARD: reviung/reviung41
      CONVERT_TO: '-e CONVERT_TO=kb2040'
  reviung41:
    taskfile: ./Taskfile-keyboard.yml
    vars:
      USERNAME: hannes
      KEYBOARD: reviung/reviung41
  34keys:
    taskfile: ./Taskfile-keyboard.yml
    vars:
      USERNAME: default
      KEYBOARD: handwired/34keys
  banana:
    taskfile: ./Taskfile-keyboard.yml
    vars:
      USERNAME: hannes
      KEYBOARD: handwired/banana
  void-ergo:
    taskfile: ./Taskfile-keyboard.yml
    vars:
      USERNAME: hannes
      KEYBOARD: handwired/void_ergo
  void9:
    taskfile: ./Taskfile-keyboard.yml
    vars:
      USERNAME: eruvanos
      KEYBOARD: handwired/void9

tasks:
  setup:
    cmds:
    - git submodule update --init --recursive
    deps:
    - init-git-sub

  init-git-sub:
    cmds:
    - git submodule add https://github.com/qmk/qmk_firmware.git
    status:
      - test -d "qmk_firmware"

  install-draw:
    cmds:
      - pipx install keymap-drawer

  default:
    cmds:
    - task: reviung34:compile
    - task: reviung41-kb2040:compile
    - task: reviung41:compile
    - task: 34keys:compile
    # - task: banana:compile
    # - task: void9:compile
    # - task: void-ergo:compile
