version: '3'

includes:
  reviung34:
    taskfile: ./Taskfile-keyboard.yml
    vars:
      USERNAME: hannes
      KEYBOARD: reviung/reviung34
  reviung41:
    taskfile: ./Taskfile-keyboard.yml
    vars:
      USERNAME: hannes
      KEYBOARD: reviung/reviung41
      CONVERT_TO: '-e CONVERT_TO=kb2040'

tasks:
  setup:
    cmds:
    - git submodule update --init --recursive
    deps:
    - init-git-sub

  init-git-sub:
    cmds:
    - git submodule add https://github.com/qmk/qmk_firmware.git
    status:
      - test -d "qmk_firmware"

  install-draw:
    cmds:
      - pipx install keymap-drawer
